"""empty message

Revision ID: 259af88e0a1d
Revises: 32ef923a7fd6
Create Date: 2025-06-12 02:38:20.551716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259af88e0a1d'
down_revision = '32ef923a7fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoices_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_sales_id'), ['sales_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('commission_rate')

    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoices_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_sales_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_date'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_created_at'))

    op.drop_table('sales_invoices')
    # ### end Alembic commands ###
