"""empty message

Revision ID: 32ef923a7fd6
Revises: 3848621d32c5
Create Date: 2025-06-12 02:33:30.528349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ef923a7fd6'
down_revision = '3848621d32c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
