"""empty message

Revision ID: 3848621d32c5
Revises: 7df3e0917377
Create Date: 2025-06-12 02:33:13.903403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3848621d32c5'
down_revision = '7df3e0917377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=10), nullable=False),
    sa.Column('pan_number', sa.String(length=11), nullable=False),
    sa.Column('bank_info', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('level')

    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_student_invoices_sales_id'), ['sales_id'], unique=False)
        batch_op.create_foreign_key(None, 'sales', ['sales_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_student_invoices_sales_id'))
        batch_op.drop_column('sales_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_updated_at'))
        batch_op.drop_index(batch_op.f('ix_sales_is_active'))
        batch_op.drop_index(batch_op.f('ix_sales_email'))
        batch_op.drop_index(batch_op.f('ix_sales_created_at'))

    op.drop_table('sales')
    # ### end Alembic commands ###
