"""Merge Changes

Revision ID: 7df3e0917377
Revises: de8e43c954cc
Create Date: 2025-06-12 01:04:28.423798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df3e0917377'
down_revision = 'de8e43c954cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mobile', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('pan_number', sa.String(length=11), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('pan_number')
        batch_op.drop_column('mobile')
        batch_op.drop_column('address')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
