"""empty message

Revision ID: 82d8da2ea7c3
Revises: 259af88e0a1d
Create Date: 2025-06-12 03:44:16.004644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82d8da2ea7c3'
down_revision = '259af88e0a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_invoices_created_at')
        batch_op.drop_index('ix_sales_invoices_date')
        batch_op.drop_index('ix_sales_invoices_sales_id')
        batch_op.drop_index('ix_sales_invoices_updated_at')

    op.drop_table('sales_invoices')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=mysql.FLOAT(),
               nullable=True)

    op.create_table('sales_invoices',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sales_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_amount', mysql.FLOAT(), nullable=False),
    sa.Column('commission_amount', mysql.FLOAT(), nullable=False),
    sa.Column('total_invoices', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], name='sales_invoices_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_sales_invoices_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_sales_invoices_sales_id', ['sales_id'], unique=False)
        batch_op.create_index('ix_sales_invoices_date', ['date'], unique=False)
        batch_op.create_index('ix_sales_invoices_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
