"""empty message

Revision ID: acae4d542c10
Revises: e16961f98e82
Create Date: 2025-06-12 00:17:32.657006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'acae4d542c10'
down_revision = 'e16961f98e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First drop the old attendances table if it exists
    try:
        op.drop_table('attendances')
    except Exception:
        pass

    # Check if attendance table exists before creating it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'attendance' not in inspector.get_table_names():
        op.create_table('attendance',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('timetable_id', sa.Integer(), nullable=False),
            sa.Column('date', sa.Date(), nullable=False),
            sa.Column('is_present', sa.Boolean(), nullable=True),
            sa.Column('is_proxy', sa.Boolean(), nullable=True),
            sa.Column('proxy_id', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['proxy_id'], ['teachers.id'], ),
            sa.ForeignKeyConstraint(['timetable_id'], ['timetable_templates.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('attendance', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_attendance_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
            batch_op.create_index(batch_op.f('ix_attendance_proxy_id'), ['proxy_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_attendance_timetable_id'), ['timetable_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_attendance_updated_at'), ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('timetable_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('occurrence_date', sa.DATE(), nullable=False),
        sa.Column('teacher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('is_present', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('is_proxy', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('proxy_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
        sa.Column('video_path', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('created_at', mysql.DATETIME(), nullable=True),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['proxy_id'], ['teachers.id'], name='attendances_ibfk_1'),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='attendances_ibfk_2'),
        sa.ForeignKeyConstraint(['timetable_id'], ['timetable_templates.id'], name='attendances_ibfk_3'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index('ix_attendances_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_attendances_timetable_id', ['timetable_id'], unique=False)
        batch_op.create_index('ix_attendances_teacher_id', ['teacher_id'], unique=False)
        batch_op.create_index('ix_attendances_occurrence_date', ['occurrence_date'], unique=False)
        batch_op.create_index('ix_attendances_created_at', ['created_at'], unique=False)

    # Drop the attendance table if it exists
    try:
        with op.batch_alter_table('attendance', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_attendance_updated_at'))
            batch_op.drop_index(batch_op.f('ix_attendance_timetable_id'))
            batch_op.drop_index(batch_op.f('ix_attendance_proxy_id'))
            batch_op.drop_index(batch_op.f('ix_attendance_date'))
            batch_op.drop_index(batch_op.f('ix_attendance_created_at'))
        op.drop_table('attendance')
    except Exception:
        pass
    # ### end Alembic commands ###
