"""empty message

Revision ID: ae55aafd6e88
Revises: 82d8da2ea7c3
Create Date: 2024-03-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae55aafd6e88'
down_revision = '82d8da2ea7c3'
branch_labels = None
depends_on = None


def upgrade():
    # First handle student_invoices table
    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('student_invoices_ibfk_2', type_='foreignkey')
        batch_op.drop_index('ix_student_invoices_sales_id')
        batch_op.alter_column('sales_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.create_index('ix_student_invoices_sales_id', ['sales_id'], unique=False)
        batch_op.create_foreign_key('student_invoices_ibfk_2', 'sales', ['sales_id'], ['id'])

    # Then handle sales_invoices table
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('sales_invoices_ibfk_1', type_='foreignkey')
        batch_op.drop_index('ix_sales_invoices_sales_id')
        batch_op.alter_column('sales_id',
               existing_type=sa.Integer(),
               nullable=False)
        batch_op.create_index('ix_sales_invoices_sales_id', ['sales_id'], unique=False)
        batch_op.create_foreign_key('sales_invoices_ibfk_1', 'sales', ['sales_id'], ['id'])

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_invoices_updated_at')

    op.drop_table('sales_invoices')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('10'))

    # ### end Alembic commands ###


def downgrade():
    # First handle sales_invoices table
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('sales_invoices_ibfk_1', type_='foreignkey')
        batch_op.drop_index('ix_sales_invoices_sales_id')
        batch_op.alter_column('sales_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.create_index('ix_sales_invoices_sales_id', ['sales_id'], unique=False)
        batch_op.create_foreign_key('sales_invoices_ibfk_1', 'sales', ['sales_id'], ['id'])

    # Then handle student_invoices table
    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('student_invoices_ibfk_2', type_='foreignkey')
        batch_op.drop_index('ix_student_invoices_sales_id')
        batch_op.alter_column('sales_id',
               existing_type=sa.Integer(),
               nullable=True)
        batch_op.create_index('ix_student_invoices_sales_id', ['sales_id'], unique=False)
        batch_op.create_foreign_key('student_invoices_ibfk_2', 'sales', ['sales_id'], ['id'])

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('commission_rate',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('10'))

    op.create_table('sales_invoices',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sales_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('total_amount', mysql.FLOAT(), nullable=False),
    sa.Column('commission_amount', mysql.FLOAT(), nullable=False),
    sa.Column('total_invoices', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], name='sales_invoices_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_sales_invoices_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_sales_invoices_sales_id', ['sales_id'], unique=False)

    # ### end Alembic commands ###
