"""empty message

Revision ID: de8e43c954cc
Revises: acae4d542c10
Create Date: 2025-06-12 00:39:26.882561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8e43c954cc'
down_revision = 'acae4d542c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_invoices', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
