"""empty message

Revision ID: e16961f98e82
Revises: 4c5add81eb40
Create Date: 2025-06-08 02:57:50.847659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16961f98e82'
down_revision = '4c5add81eb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_present', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.drop_column('is_present')

    # ### end Alembic commands ###
